# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Phone number'),
        ),
    ]
