# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_auto_20170609_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=users_app.models.get_upload_path),
        ),
    ]
