# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20170721_1739'),
        ('users_app', '0009_auto_20170707_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dispensary',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Dispensary'),
        ),
    ]
