# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0011_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users_app.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
