# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 00:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170616_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 7, 17, 0, 55, 50, 57160)),
        ),
    ]
