# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20170617_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='category',
            field=models.CharField(choices=[('in', 'Indica'), ('sa', 'Sativa'), ('hy', 'Hybrid'), ('cbd', 'CBD'), ('co', 'Concentrates'), ('ed', 'Edibles')], default='in', max_length=3),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 7, 22, 14, 44, 50, 296404)),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='state',
            field=models.CharField(max_length=30, verbose_name='State abbreviation'),
        ),
    ]
