# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20170622_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 8, 5, 20, 54, 49, 790617)),
        ),
    ]
