# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20170706_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30, verbose_name='State abbreviation')),
                ('street_address', models.CharField(max_length=90, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dispensary',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dispensary',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='dispensary',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='dispensary',
            name='state',
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 8, 6, 8, 23, 3, 701072)),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Location'),
        ),
    ]
