# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20170707_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 8, 10, 15, 4, 3, 804508)),
        ),
    ]
