# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20170721_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 8, 20, 17, 32, 0, 77025)),
        ),
    ]
