# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20170721_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensary',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 8, 20, 17, 48, 44, 390217)),
        ),
    ]
