# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20170721_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=main_app.models.get_deal_upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 8, 24, 15, 16, 12, 635018)),
        ),
        migrations.AddField(
            model_name='dealimage',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.Deal'),
        ),
    ]
