# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 21:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20170725_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 8, 24, 21, 23, 46, 989878)),
        ),
    ]
