# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20170725_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 16, 56, 52, 59245)),
        ),
        migrations.AlterField(
            model_name='dealimage',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
