# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20170727_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 17, 5, 48, 171420)),
        ),
        migrations.AlterField(
            model_name='dealimage',
            name='image',
            field=models.ImageField(null=True, upload_to=main_app.models.get_deal_upload_path),
        ),
    ]
