# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20170727_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 17, 45, 0, 373570)),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (2, 'Pending'), (0, 'Inactive')], default=2, max_length=1),
        ),
    ]
