# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20170728_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Used')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 8, 28, 22, 48, 33, 690774)),
        ),
    ]
