# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20170729_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensary',
            name='secret',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 8, 28, 23, 8, 21, 317703)),
        ),
    ]
