# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20170821_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensary',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 9, 21, 13, 34, 3, 675010)),
        ),
    ]
