# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 08:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20170827_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 9, 28, 8, 35, 39, 647789)),
        ),
    ]
