# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20170829_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_click', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='dispensary',
            name='working_from',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='working_to',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 9, 28, 22, 8, 4, 829120)),
        ),
    ]
