# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 15:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0030_auto_20170829_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensaryPatientPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('dispensary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_points', to='main_app.Dispensary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensaries_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 10, 6, 15, 17, 46, 243542)),
        ),
    ]
