# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 15:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20170906_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='type',
            field=models.CharField(choices=[(0, 'Regular'), (1, 'Featured'), (2, 'Waiting')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_expires',
            field=models.DateField(default=datetime.datetime(2017, 10, 9, 15, 3, 9, 971872)),
        ),
    ]
